services:
  postgres:
    image: postgres:16-alpine
    container_name: dev_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TeacherSubAppDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: dev_pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/TeacherSubAppDb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: