// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeacherSubApp.Api.Data;

#nullable disable

namespace TeacherSubApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.EventKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsStandby")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EventName")
                        .IsUnique()
                        .HasDatabaseName("IX_EventKeys_Name_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("IsStandby")
                        .IsUnique()
                        .HasDatabaseName("IX_EventKeys_IsStandby_Active_Unique")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"IsStandby\" = true");

                    b.HasIndex("IsSupport")
                        .IsUnique()
                        .HasDatabaseName("IX_EventKeys_IsSupport_Active_Unique")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"IsSupport\" = true");

                    b.ToTable("EventKeys", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventKeys_ExclusiveFlags", "NOT (\"IsSupport\" = true AND \"IsStandby\" = true)");
                        });
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<int?>("Section")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("IX_Classes_DisplayName_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Grade", "Section")
                        .IsUnique()
                        .HasDatabaseName("IX_Classes_GradeSection_Active")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"Grade\" IS NOT NULL AND \"Section\" IS NOT NULL");

                    b.ToTable("Classes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Class_GradeSection_Pair", "(\"Grade\" IS NULL AND \"Section\" IS NULL) OR (\"Grade\" IS NOT NULL AND \"Section\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Class_Grade_Positive", "\"Grade\" > 0");

                            t.HasCheckConstraint("CK_Class_Section_Positive", "\"Section\" > 0");
                        });
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Subjects_Name_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Substitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsenceId")
                        .HasColumnType("integer");

                    b.Property<string>("AbsentTeacherNameAtTimeOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AbsentTeacherSubjectAtTimeOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassNameAtTimeOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlgorithmMatch")
                        .HasColumnType("boolean");

                    b.Property<int>("PeriodNumberAtTimeOfService")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("SubstituteTeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("SubstituteTeacherNameAtTimeOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubstituteTeacherSubjectAtTimeOfService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherAbsenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubstituteTeacherId");

                    b.HasIndex("TeacherAbsenceId");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSupervisor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Teachers_Name_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Teachers_SubjectId")
                        .HasFilter("\"SubjectId\" IS NOT NULL");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.TeacherAbsence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AbsenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAbsences");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_WeeklySchedules_ClassId")
                        .HasFilter("\"ClassId\" IS NOT NULL");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_WeeklySchedules_EventId")
                        .HasFilter("\"EventId\" IS NOT NULL");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_WeeklySchedules_TeacherId");

                    b.HasIndex("DayOfWeek", "PeriodNumber")
                        .HasDatabaseName("IX_WeeklySchedules_DayPeriod_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("ClassId", "DayOfWeek", "PeriodNumber")
                        .HasDatabaseName("IX_WeeklySchedules_ClassSlot_Active")
                        .HasFilter("\"ClassId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("TeacherId", "DayOfWeek", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_WeeklySchedules_TeacherSlot_Active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("WeeklySchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedule_ClassOrEvent", "\"ClassId\" IS NOT NULL OR \"EventId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Schedule_DayOfWeek", "\"DayOfWeek\" >= 1 AND \"DayOfWeek\" <= 5");

                            t.HasCheckConstraint("CK_Schedule_Period", "\"PeriodNumber\" >= 1 AND \"PeriodNumber\" <= 7");
                        });
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Substitution", b =>
                {
                    b.HasOne("TeacherSubApp.Api.Data.Models.Teacher", "SubstituteTeacher")
                        .WithMany("Substitutions")
                        .HasForeignKey("SubstituteTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Substitutions_SubstituteTeacher");

                    b.HasOne("TeacherSubApp.Api.Data.Models.TeacherAbsence", "TeacherAbsence")
                        .WithMany("Substitutions")
                        .HasForeignKey("TeacherAbsenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherSubApp.Api.Data.Models.WeeklySchedule", "WeeklySchedule")
                        .WithMany("Substitutions")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Substitutions_WeeklySchedule");

                    b.Navigation("SubstituteTeacher");

                    b.Navigation("TeacherAbsence");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Teacher", b =>
                {
                    b.HasOne("TeacherSubApp.Api.Data.Models.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Teachers_Subjects");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.TeacherAbsence", b =>
                {
                    b.HasOne("TeacherSubApp.Api.Data.Models.Teacher", "Teacher")
                        .WithMany("Absences")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TeacherAbsences_Teachers");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.WeeklySchedule", b =>
                {
                    b.HasOne("TeacherSubApp.Api.Data.Models.SchoolClass", "SchoolClass")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_WeeklySchedules_Classes");

                    b.HasOne("TeacherSubApp.Api.Data.Models.EventKey", "EventKey")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_WeeklySchedules_EventKeys");

                    b.HasOne("TeacherSubApp.Api.Data.Models.Teacher", "Teacher")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WeeklySchedules_Teachers");

                    b.Navigation("EventKey");

                    b.Navigation("SchoolClass");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.EventKey", b =>
                {
                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.SchoolClass", b =>
                {
                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Subject", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.Teacher", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Substitutions");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.TeacherAbsence", b =>
                {
                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("TeacherSubApp.Api.Data.Models.WeeklySchedule", b =>
                {
                    b.Navigation("Substitutions");
                });
#pragma warning restore 612, 618
        }
    }
}
